name: flutter_applet
description: A new Flutter project.

publish_to: 'none'

version: 2.1.0+210

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  css_colors: ^1.1.1
  fluttertoast: ^8.0.9
  url_launcher: ^6.1.4
  mqtt_client: ^9.6.8
  device_info_plus: ^4.0.0
  wakelock: ^0.6.1+2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/banzhuan.jpg

  # To add custom fonts to your application, add a fonts section here, in this "flutter" section.
  # https://flutter.dev/custom-fonts/#from-packages
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
