name: flutter_achieve
description: A new Flutter project.

publish_to: 'none'

version: 2.4.0+20400

environment:
  sdk: '>=2.18.0 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  css_colors: ^1.1.1
  fluttertoast: ^8.0.9
  url_launcher: ^6.1.5
  mqtt_client: ^9.7.2
  device_info_plus: ^4.1.2
  wakelock: ^0.6.2
  shared_preferences: ^2.0.15
#  permission_handler: ^10.0.0
  path_provider: ^2.0.11
  file_picker: ^5.0.1
  ftpconnect: ^1.0.1
  fluent_ui: ^3.12.0
#  window_size:
#    git:
#      url: https://github.com/google/flutter-desktop-embedding.git
#      path: plugins/window_size

dev_dependencies:
  # https://flutter.cn/docs/cookbook/testing/widget/introduction
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # https://flutter.dev/assets-and-images/#from-packages
  assets:
    - assets/images/banzhuan.jpg
  # https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Fira Code
      fonts:
        - asset: assets/fonts/FiraCode.ttf
        - asset: assets/fonts/FiraCode-Bold.ttf
          weight: 700
