name: flutter_applet
description: A new Flutter project.

publish_to: 'none'

version: 2.2.0+220

environment:
  sdk: ">=2.17.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  css_colors: ^1.1.1
  fluttertoast: ^8.0.9
  url_launcher: ^6.1.4
  mqtt_client: ^9.6.8
  device_info_plus: ^4.0.0
  wakelock: ^0.6.1+2
  shared_preferences: ^2.0.15

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  # https://flutter.dev/assets-and-images/#from-packages
  assets:
    - assets/images/banzhuan.jpg
  # https://flutter.dev/custom-fonts/#from-packages
  fonts:
    - family: Fira Code
      fonts:
        - asset: assets/fonts/FiraCode.ttf
        - asset: assets/fonts/FiraCode-Bold.ttf
          weight: 700
